name: "Label Syncer"
description: "Sync GitHub labels in the declarative way."
author: "micnncim"
inputs:
  manifest:
    description: "File path of YAML manifest for labels"
    required: false
    default: ".github/labels.yml"
  repository:
    description: "The repo to sync labels on (defaults to current repo)"
    required: false
  token:
    description: "An alternative GitHub token to use instead"
    required: false
  prune:
    description: "Remove unmanaged labels from repository"
    required: false
    default: true
  httpAuthUsername:
    description: "A HTTP basic auth username to be used when downloading referenced label files"
    required: false
  httpAuthPassword:
    description: "A HTTP basic auth password to be used when downloading referenced label files"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: circle
  color: black
